### ISSUE TITLE
Best way to do cleanup

### ISSUE THREAD

**Issue by sharafian** [emschwartz/ilp-protocol-paystream#9] opened 2018-02-15 00:27 UTC
Currently, in an SPSP server I create a new receiver socket on every single query. After a while they close if there is no activity, but it seems like an SPSP endpoint could be overwhelmed by queries if it keeps the sockets around for a while. Also if the sender begins to send but then stops, the socket does not appear to time out.

**Comment by emschwartz** [comment] 2018-02-15 00:50
Duplicate of https://github.com/emschwartz/ilp-protocol-paystream/issues/1

**Closed as completed by emschwartz** 2018-02-15 00:50 UTC
